name: Build and Test

on: push

jobs:
  test:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.10.4"
          enable-stack: true
          stack-version: "latest"

      - name: Cache ~/.stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('**.yaml') }}
  
      - name: Cache .stack-work
        uses: actions/cache@v2
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-local-${{ hashFiles('**.yaml') }}
  
      - name: Build Package
        run: |
          stack build --system-ghc --fast
  
      - name: Test Package
        run: |
          stack test --system-ghc --fast
